[user]
username = "invra"
displayName = "invra"
initialPassword = "123456"

[system]
greeter = "gdm"
hostname = "NixOS"
timezone = "Australia/Sydney"
locale = "en_AU.UTF-8"
kernelParams = ["intel_iommu=on"]

[system.networking]
networkmanager = false
firewallEnabled = false
dhcpEnabled = false

[[system.networking.interfaces]]
type = "BRIDGE"
name = "br0"
interfaces = ["enp7s0"]
dhcpEnabled = true

[system.graphics]
blacklists = ["nouveau", "nvidia"]
wanted = []

[system.services]
ssh.enable = true
mongodb.enable = true

[desktop]
[desktop.plasma]
enable = true

[desktop.hyprland]
enable = true

[[desktop.hyprland.monitors]]
name = "DP-3"
resolution = "2560x1440"
refreshRate = 180
position = "0x0"
scale = 1

[development]
[development.git]
username = "InvraNet"
types = ["GitLab", "GitHub"]
email = "identificationsucks@gmail.com"
defaultBranch = "main"
