[user]
username = "peter"
displayName = "peter"
initialPassword = "123456"

[system]
greeter = "gdm"
hostname = "NixOS"
timezone = "Australia/Sydney"
locale = "en_AU.UTF-8"
kernelParams = ["intel_iommu=on"]

[system.dock]
autohide = true
autoHideDelay = 0.45
orientation = "bottom"

[system.networking]
networkmanager = true
dhcpEnabled = true
firewallEnabled = false

[system.interfaces]

[system.graphics]
blacklists = ["nouveau", "nvidia"]
wanted = ["amdgpu"]

[system.services]
ssh.enable = true
mongodb.enable = true

[desktop]
[desktop.plasma]
enable = true

[desktop.hyprland]
enable = true

[[desktop.hyprland.monitors]]
name = "eDP-1"
resolution = "1920x1080"
refreshRate = 120
position = "0x0"
scale = 1

[development]
[development.git]
username = "InvraNet"
types = ["GitLab", "GitHub"]
email = "identificationsucks@gmail.com"
defaultBranch = "main"
