[user]
username = "user"
displayName = "user"
initialPassword = "123456"

[system]
hostname = "NixOS"
timezone = "Australia/Sydney"
locale = "en_AU.UTF-8"
kernelParams = ["intel_iommu=on"]

[system.networking]
networkmanager = true
dhcpEnabled = true

[system.interfaces]

[system.graphics]
blacklists = ["nouveau", "nvidia"]
wanted = []

[system.services]
ssh.enable = true
mongodb.enable = true

[desktop]
[desktop.hyprland]
enable = true
wallpapers = ["eDP-1,/home/user/.wallpapers/nature.jpg"]

[[desktop.hyprland.monitors]]
name = "eDP-1"
resolution = "1920x1200"
refreshRate = 60
position = "0x0"
scale = 1

[development]
[development.git]
username = "InvraNet"
types = ["GitLab", "GitHub"]
email = "identificationsucks@gmail.com"
defaultBranch = "main"
