format = """
[](fg:#443943)\
[ 󱄅  ](bg:#443943 fg:#ebbcba)\
$username\
[](bg:#3c354c fg:#443943)\
$directory\
[](fg:#3c354c bg:#463a36)\
$git_branch\
$git_status\
[](fg:#463a36 bg:#26233a)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#26233a bg:#2a273f)\
$time\
[](fg:#2a273f)\
\n$character"""

[character]
success_symbol = "[ 󱞪](bold green)"
error_symbol = "[ 󱞪](bold red)"

[username]
show_always = true
style_root = "red bold"
style_user = "bg:#443943 fg:#ebbcba bold"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#c4a7e7 bg:#3c354c"
format = "[ $path ]($style)"
truncation_length = 30
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"dev" = " "
"Dev" = " "
"developer" = " "
"Developer" = " "
".nix" = "󱄅 "
"nix" = "󱄅 "
"dotfiles" = " "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#f6c177 bg:#463a36)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#f6c177 bg:#463a36)]($style)'

[nodejs]
symbol = ""
style = "bg:#583e47"
format = '[[ $symbol ($version) ](fg:#908caa bg:#26233a)]($style)'

[rust]
symbol = ""
style = "bg:#26233a"
format = '[[ $symbol ($version) ](fg:#908caa bg:#26233a)]($style)'

[golang]
symbol = ""
style = "bg:#26233a"
format = '[[ $symbol ($version) ](fg:#908caa bg:#26233a)]($style)'

[php]
symbol = ""
style = "bg:#26233a"
format = '[[ $symbol ($version) ](fg:#908caa bg:#26233a)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#584951"
format = '[[   $time ](fg:#908caa bg:#2a273f)]($style)'
