[package]
name = "invra-nix-automation"
version = "0.0.1"
edition = "2024"
authors = [ "Invra" ]

[[bin]]
name = "bootstrap-darwin"
path = "src/nix-darwin.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[dependencies]
clap = "4.5.41"
colored = "3.0.0"
os_info = "3.12.0"
