[dependencies]
clap = {version = "4.5.43", features = ["derive"]}
core-foundation = "0.10.1"
core-foundation-sys = "0.8.7"
objc2 = "0.6.1"

[package]
name = "menus"
version = "0.1.0"
edition = "2024"
